export interface BreedOption {
  value: string;
  label: string;
}

export const DOG_BREEDS: BreedOption[] = [
  { value: "labrador-retriever", label: "Labrador Retriever" },
  { value: "german-shepherd", label: "German Shepherd" },
  { value: "golden-retriever", label: "Golden Retriever" },
  { value: "bulldog", label: "Bulldog" },
  { value: "beagle", label: "Beagle" },
  { value: "poodle", label: "Poodle" },
  { value: "rottweiler", label: "Rottweiler" },
  { value: "yorkshire-terrier", label: "Yorkshire Terrier" },
  { value: "boxer", label: "Boxer" },
  { value: "dachshund", label: "Dachshund" },
  { value: "siberian-husky", label: "Siberian Husky" },
  { value: "doberman-pinscher", label: "Doberman Pinscher" },
  { value: "great-dane", label: "Great Dane" },
  { value: "australian-shepherd", label: "Australian Shepherd" },
  { value: "cavalier-king-charles-spaniel", label: "Cavalier King Charles Spaniel" },
  { value: "miniature-schnauzer", label: "Miniature Schnauzer" },
  { value: "shih-tzu", label: "Shih Tzu" },
  { value: "boston-terrier", label: "Boston Terrier" },
  { value: "pembroke-welsh-corgi", label: "Pembroke Welsh Corgi" },
  { value: "bernese-mountain-dog", label: "Bernese Mountain Dog" },
  { value: "brittany", label: "Brittany" },
  { value: "cocker-spaniel", label: "Cocker Spaniel" },
  { value: "pug", label: "Pug" },
  { value: "english-springer-spaniel", label: "English Springer Spaniel" },
  { value: "mastiff", label: "Mastiff" },
  { value: "basset-hound", label: "Basset Hound" },
  { value: "border-collie", label: "Border Collie" },
  { value: "bichon-frise", label: "Bichon Frise" },
  { value: "weimaraner", label: "Weimaraner" },
  { value: "newfoundland", label: "Newfoundland" },
  { value: "chihuahua", label: "Chihuahua" },
  { value: "akita", label: "Akita" },
  { value: "st-bernard", label: "St. Bernard" },
  { value: "collie", label: "Collie" },
  { value: "bloodhound", label: "Bloodhound" },
  { value: "rhodesian-ridgeback", label: "Rhodesian Ridgeback" },
  { value: "vizsla", label: "Vizsla" },
  { value: "whippet", label: "Whippet" },
  { value: "west-highland-white-terrier", label: "West Highland White Terrier" },
  { value: "australian-cattle-dog", label: "Australian Cattle Dog" },
  { value: "alaskan-malamute", label: "Alaskan Malamute" },
  { value: "papillon", label: "Papillon" },
  { value: "samoyed", label: "Samoyed" },
  { value: "irish-setter", label: "Irish Setter" },
  { value: "jack-russell-terrier", label: "Jack Russell Terrier" },
  { value: "greyhound", label: "Greyhound" },
  { value: "great-pyrenees", label: "Great Pyrenees" },
  { value: "bullmastiff", label: "Bullmastiff" },
  { value: "shiba-inu", label: "Shiba Inu" },
];
